services:
  currency-mysql:
    image: mysql:8.0
    container_name: currency-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - exchange_mysql_data:/var/lib/mysql
    networks:
      - exchange-net

  currency-app:
    build: .
    container_name: currency-app
    depends_on:
      - currency-mysql
    ports:
      - "8080:8080"
    environment:
      TZ: Asia/Tokyo
      JAVA_OPTS: "-Duser.timezone=Asia/Tokyo"
      SPRING_DATASOURCE_URL: jdbc:mysql://currency-mysql:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Tokyo
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      EXCHANGE_API_KEY: ${EXCHANGE_API_KEY}
    networks:
      - exchange-net

volumes:
  exchange_mysql_data:

networks:
  exchange-net: